name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
      - 'feature/ci-cd'
  push:
    branches:
      - main
      - 'feature/ci-cd'
  workflow_dispatch:  # Allow manual triggering

# Define environment-specific variables
env:
  PULUMI_VERSION: '3.121.0'
  STACK_NAME: dev

# Concurrency group ensures that only one workflow runs at a time
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: false

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - id: set-env
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == "refs/heads/feature/ci-cd" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          else
            echo "environment=unknown" >> $GITHUB_OUTPUT
            echo "No deployment will be triggered for this branch"
          fi

  deploy:
    needs: determine-environment
    # Only run if environment is known and (CI workflow succeeded or direct push)
    if: >
      needs.determine-environment.outputs.environment != 'unknown' && 
      (github.event_name == 'push' || 
       github.event_name == 'workflow_dispatch' || 
       (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'))
    runs-on: ubuntu-latest
    # Use the determined environment
    environment: ${{ needs.determine-environment.outputs.environment }}
    permissions:
      id-token: write  # Required for OIDC auth with AWS
      contents: read   # Required to checkout the code
    
    steps:
      # Debug GitHub context
      - name: Debug GitHub context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub ref_name: ${{ github.ref_name }}"
          
      - uses: actions/checkout@v4
      
      # Debug AWS Account ID
      - name: Debug AWS Account ID
        run: |
          echo "Using AWS Account ID: ${{ secrets.AWS_ACCOUNT_ID }}"
      
      # Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          aws-region: ${{ secrets.AWS_REGION }}
      
      # For workflow_run events - download artifacts from workflow
      - name: Download artifacts from workflow (workflow_run)
        if: github.event_name == 'workflow_run'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI
          workflow_conclusion: success
          branch: ${{ github.event.workflow_run.head_branch || github.ref_name }}
          path: artifacts

      # For push and workflow_dispatch - build Lambda packages
      - name: Build Lambda packages (push or workflow_dispatch)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          chmod +x ./build_lambda_packages.sh
          ./build_lambda_packages.sh

      # Move or verify artifacts
      - name: Organize artifacts
        run: |
          # Create directories first
          mkdir -p api/build/packages/
          mkdir -p worker/build/packages/
          
          # For workflow_run, move the downloaded artifacts
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            mv artifacts/api-package/* api/build/packages/ || echo "No API package found"
            mv artifacts/worker-package/* worker/build/packages/ || echo "No worker package found"
          fi
          
          # Verify packages exist
          echo "API packages:"
          ls -la api/build/packages/
          echo "Worker packages:"
          ls -la worker/build/packages/
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      # Install uv and dependencies
      - name: Install uv
        run: |
          pip install --upgrade pip
          pip install uv
      
      - name: Install dependencies
        run: |
          cd provisioning
          uv sync
      
      - name: Deploy with Pulumi
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: yorrickjansen/${{ env.STACK_NAME }}
          args: '-y'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    
      # Verify deployment
      - name: Test deployed API endpoint
        if: ${{ success() }}
        run: |
          cd provisioning
          ENDPOINT=$(pulumi stack output apigateway-rest-endpoint)
          curl -f "${ENDPOINT}/examples/hello" || exit 1